FORMAT: 1A
HOST: http://productsapi14.apiblueprint.org/

# Products API

Products API is a simple API allowing consumers to view product.

## Products Collection [/products]

### List All Products [GET]

+ Response 200 (application/json)

        [
            {
                "count": 5,
                "data": [
                    {
                        "product_id": "PR-0001"
                        "name": "Spa by Marga tilaar",
                        "price": "Rp 100.000,00
                        "description": "Details details details details"
                    },
                    {
                        "product_id": "PR-0002"
                        "name": "Spa by Wonder Spa",
                        "price": "Rp 150.000,00
                        "description": "Details details details details"
                    },
                    {
                        "product_id": "PR-0003"
                        "name": "Spa by Best Spa",
                        "price": "Rp 200.000,00
                        "description": "Details details details details"
                    },
                    {
                        "product_id": "PR-0004"
                        "name": "Spa by The New Spa",
                        "price": "Rp 250.000,00
                        "description": "Details details details details"
                    },
                    {
                        "product_id": "PR-0005"
                        "name": "Spa by All Spa",
                        "price": "Rp 300.000,00
                        "description": "Details details details details"
                    },
                    
                ]
            }
        ]